### ISSUE TITLE
Approvazione project plan

### ISSUE THREAD

**Issue by andrearoota** [andrearoota/SoftwareEngineeringProject#7]
Gent.le prof.re @garganti,
Le richiediamo l'approvazione del project plan situato all'interno della directory `documentation`.

Cordiali saluti

**Comment by garganti** [comment]
approvato. Se riuscite ad usare un db embedded meglio ... per il resto molto chiaro il tutto.

**Comment by andrearoota** [comment]
> approvato. Se riuscite ad usare un db embedded meglio ... per il resto molto chiaro il tutto.

Abbiamo scelto PostgreSQL perché consigliatoci durante i corsi di Databases come database open source, grazie all'ORM di Laravel possiamo implementare SQLite senza alcuna difficoltà; nel prossimo sprint mi occuperò della migrazione.
